version: "3.9"
services:
    app:
        platform: "linux/amd64"
        build:
            context: .
            dockerfile: Dockerfile
            args:
                NEXT_PUBLIC_APP_URL: "http://localhost:3000"
                NEXT_PUBLIC_API: "https://4ilk3v7wbk.execute-api.eu-west-1.amazonaws.com/dev/"
        working_dir: /app
        ports:
            - "3000:3000"
        image: t3-app
