import Providers from "@/lib/provider";
import "./globals.css";
import { Metadata } from "next";
import { Inter } from "next/font/google";
import { ReactNode } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
interface ILayout {
    children: ReactNode;
}

export default function RootLayout({ children }: ILayout) {
    return (
        <html lang="it">
            <Providers>
                <body className={inter.className}>{children}</body>
            </Providers>
        </html>
    );
}
