export const API_ENDPOINTS = {
    OTHERS: {
        MENUS: {
            SUBMENU: { GET: "app/api/menu/sub" },
            MENU: { GET: "app/api/menu/main" },
        },
        AGGIUNTA_ACCOUNT: { CREATE: "app/api/account/new" },
        STAMPA: {
            GET_ALL: "app/api/impostazioni/stampa/view",
            UPDATE_BY_ID: "app/api/impostazioni/stampa/update",
            CREATE: "app/api/impostazioni/stampa/new",
            GET_STANDARD: "app/api/impostazioni/stampa/view/standard",
        },
        ESIGIBILITA: {
            GET_ESIGIBILITA: "app/api/others/esigibilita/view",
            GET_ESIGIBILITA_COMBO: "app/api/others/esigibilita/view/combo",
        },
        CONTI: {
            GET_PIANO_CONTI: "app/api/others/pianodelconti/view",
            GET_PIANO_CONTI_COMBO: "app/api/others/pianodelconti/view/combo",
            GET_CONTI: "app/api/others/conto/view",
            GET_CONTI_COMBO: "app/api/others/conto/view/combo",
        },
    },

    ANAGRAFICO: { 
        TARIFFARIO: {
            UPDATE: "app/api/anagrafica/tariffario/update",
            GET_BY_ID: "app/api/anagrafica/tariffario/view",
        },
        BANCHE: {
            GET_ALL: "app/api/anagrafica/banca/view",
            GET_BY_ID: "app/api/anagrafica/banca/view",
            GET_LISTA_CONTI_BY_ID: "app/api/anagrafica/banca/view/contiBanca",
            EDIT_DEFAULT_CONTO_BY_ID: "app/api/anagrafica/banca/update/conto/setDefault",
            EDIT_BANCHE_BY_ID: "app/api/anagrafica/banca/update",
            CREATE_BANCHE: "app/api/anagrafica/banca/new",
            CREATE_CONTO_FROM_BANCA: "app/api/anagrafica/banca/conto/new",
            DELETE_BANCHE_BY_ID: "app/api/anagrafica/banca/delete",
            DELETE_CONTO_BY_ID: "app/api/anagrafica/banca/conto/delete",
        },
        CLIENTI: {
            GET_ALL: "app/api/anagrafica/clienti/view",
            CREATE_CLIENTI: "app/api/anagrafica/clienti/new",
            EDIT_CLIENTI_BY_ID: "app/api/anagrafica/clienti/update",
            DELETE_CLIENTI_BY_ID: "app/api/anagrafica/clienti/delete",
            IMPORTA_CLIENTE_BY_ID: "app/api/anagrafica/clienti/import/cliente",
            GET_ALL_TARIFFARIO: "app/api/anagrafica/tariffario/clienti/view",
        },
        FORNITORI: {
            GET_ALL: "app/api/anagrafica/fornitori/view",
            DELETE_FORNITORI_BY_ID: "app/api/anagrafica/fornitori/new",
            CREATE_FORNITORI: "app/api/anagrafica/fornitori/update",
            EDIT_FORNITORI_BY_ID: "app/api/anagrafica/fornitori/delete",
            IMPORTA_FORNITORE_BY_ID: "app/api/anagrafica/fornitori/import/fornitore",
        },
        SERVIZI: {
            GET_ALL: "app/api/anagrafica/servizi/view",
            DELETE: "app/api/anagrafica/servizi/delete",
            CREATE: "app/api/anagrafica/servizi/new",
            UPDATE: "app/api/anagrafica/servizi/update",
        },
    },
    DATI_ESTERNI: {
        TRACCIATI: {
            GET_ALL: "app/api/impostazioni/tracciati/view",
            DELETE_BY_ID: "app/api/impostazioni/tracciati/delete",
        },
        RICONCILIAZIONE: null,
    },
    DOCUMENTI: {
        FATTURE_ACQUISTO: null,
        FATTURE_PROFORMA: null,
        FATTURE_VENDITA: null,
        LIQUIDAZIONE_IVA: null,
    },
    IMPOSTAZIONI: {
        GENERALI: {
            GET_ALL: "app/api/impostazioni/view",
            UPDATE_BY_ID: "app/api/impostazioni/update",
            CREATE: "app/api/impostazioni/new",
        },
        FATTURE: {
            GET_ALL: "app/api/impostazioni/fattura/view",
            UPDATE_BY_ID: "app/api/impostazioni/fattura/update",
            CREATE: "app/api/impostazioni/fattura/new",
        },
        CATEGORIA_SPESA: {
            GET_ALL: "app/api/impostazioni/categoria/spesa/view",
            CREATE: "app/api/impostazioni/categoria/spesa/new",
            DELETE_BY_ID: "app/api/impostazioni/categoria/spesa/delete",
            UPDATE_BY_ID: "app/api/impostazioni/categoria/spesa/update",
        },
        VOCI_SPESA: {
            GET_VOCI_SPESA: "app/api/impostazioni/vociSpesa/view",
            GET_VOCI_SPESA_COMBO: "app/api/impostazioni/vociSpesa/view/combo",
            DELETE_IMPOSTAZIONI_SPESA_BY_ID: "app/api/impostazioni/vociSpesa/delete",
        },
        IVA: {
            GET_ALL: "app/api/impostazioni/iva/view",
            GET_ALL_COMBO: "app/api/impostazioni/iva/view/combo",
            UPDATE_BY_ID: "app/api/impostazioni/iva/update",
        },

        TIPI_PAGAMENTO: {
            GET_ALL: "app/api/impostazioni/tipiPagamento/view",
            GET_ALL_COMBO: "app/api/impostazioni/tipiPagamento/view/combo",
            UPDATE_BY_ID: "app/api/impostazioni/tipiPagamento/update",
        },
        CONDIZIONI_PAGAMENTO: {
            GET_ALL: "app/api/impostazioni/condizioniPagamento/view",
            GET_COMBO_ALL: "app/api/others/condizioniPagamento/view/combo",
            UPDATE_BY_ID: "app/api/impostazioni/condizioniPagamento/update",
        },
    },
    REPORT: {
        DASHBOARD: {
            GET_BACKLOG: "app/api/others/report/dashboard/backlog",
            CREATE_DASHBOARD_ATTIVITA_ESEGUITE: "app/api/others/report/dashboard/attivita",
            CREATE_DASHBOARD_FATTURATO_MENSILE: "app/api/others/report/dashboard/fatturato/mensile",
            CREATE_DASHBOARD_AGING: "app/api/others/report/dashboard/aging",
        },
        ANALISI_CLIENTI: {
            GET_DETTAGLI_CLIENTI: "app/api/others/report/analisi/dettagli-clienti",
            GET_ANALISI_PAGAMENTI_BY_ID: "app/api/others/report/analisi/analisi-pagamenti",
            EDIT_FATTURATO_MENSILE_BY_ID: "app/api/anagrafica/clienti/update",
            GET_CREATED_ANALISI_CLIENTI: "app/api/others/report/analisi/analisi-clienti",
        },
        PREVISIONALE: null,
    },
    SCADENZE: {
        ANTICIPI: {
            GET_ALL: "app/api/scadenze/anticipi/view",
            GET_CREATED_PDF_ANTICIPI: "app/api/scadenze/anticipi/pdf",
            DELETE_ANTICIPI_BY_ID: "app/api/scadenze/anticipi/delete",
        },
        GIROCONTI: {
            GET_ALL: "app/api/scadenze/giroconto/view",
            DELETE_GIROCONTO_BY_ID: "app/api/scadenze/giroconto/delete",
            CREATE_GIROCONTO: "app/api/scadenze/giroconto/new",
            EDIT_GIROCONTO_BY_ID: "app/api/scadenze/giroconto/edit",
        },
        ESTRATTO_CONTO: {
            GET_ALL: "app/api/scadenze/estrattoConto/view",
            GET_CREATED_ESTRATTO_CONTO_PDF: "app/api/scadenze/estrattoConto/pdf",
            SET_DATA_RICONCILIAZIONE_BY_ID: "app/api/scadenze/estrattoConto/edit",
        },
        PAGAMENTI: {
            GET_ALL: "app/api/scadenze/pagamenti/view",
            GET_CREATED_PDF: "app/api/scadenze/pagamenti/pdf",
            CREATE_DISTINTA_PAGAMENTO: "app/api/scadenze/pagamenti/newDistinta",
            CREATE_SCADENZIARIO_PAGAMENTO: "app/api/scadenze/pagamenti/newScadenziario",
            UPDATE_SCADENZIARIO_PAGAMENTO: "app/api/scadenze/pagamenti/edit",
            UPDATE_STATE_PAGAMENTO: "app/api/scadenze/pagamenti/edit/pagato",
        },
        INCASSI: {
            GET_CREATED: "app/api/scadenze/incassi/view",
            DELETE_BY_ID: "app/api/scadenze/incassi/view",
            SUBMIT_AGGIUNTA: "app/api/scadenze/incassi/new",
            SET_PAGATO: "app/api/scadenze/incassi/edit/pagato",
            SET_PAGAMENTO_PARZIALE: "app/api/scadenze/incassi/edit/pagato/parziale",
            EDIT_INCASSO: "app/api/scadenze/incassi/edit",
        },
    },
    TIMESHEET: {
        ATTIVITA: {
            GET_ATTIVITA_BY_ID: "app/api/others/attivita/get",
            GET_ATTIVITA_ALL: "app/api/others/attivita/view",
            CREATE_ATTIVITA: "app/api/others/attivita/new",
            UPDATE_ATTIVITA_BY_ID: "app/api/others/attivita/update",
            DELETE_ATTIVITA_BY_ID: "app/api/others/attivita/delete",
        },
        FATTURAZIONE: null,
        PROGETTO: {
            GET_PROGETTO_BY_ID: "app/api/others/attivita-progetto/get",
            GET_PROGETTI: "app/api/others/attivita-progetto/view",
            CREATE_PROGETTO: "app/api/others/attivita-progetto/new",
            UPDATE_PROGETTO_BY_ID: "app/api/others/attivita-progetto/update",
            DELETE_PROGETTO_BY_ID: "app/api/others/attivita-progetto/delete",
        },
    },
    UTENTE: {
        TENANT: { 
            GET_BY_ID: "api/tenant/view",
            GET_OWN: "api/tenant/list/own",
            GET_SHARED: "api/tenant/list/shared",
            CREATE: "api/tenant/new",
            DELETE_BY_ID: "api/tenant/delete",
            MANAGE_PLAN_BY_ID: "api/tenant/changePlan",
            SET_TENANT_DOMAIN: "api/tenant/setDomain",
        },
        USER_DATA_AUTH: {
            GET_ME: "api/user/me",
            GET_LOGOUT: "api/user/logout",
            REGISTER: "api/user/auth/register",
            LOGIN_CREATE_TOKEN: "oauth/token",
            GET_AUTHORIZE_CALLBACK: "oauth/authorize",
            REFRESH_SESSION: "oauth/token/refresh",
            CHALLENGE_USER_APPROVE_AUTH: "oauth/authorize",
            CHALLENGE_USER_DENY_AUTH: "oauth/authorize",
            GET_USER_AUTH_TOKENS: "oauth/tokens",
            DELETE_USER_AUTH_TOKENS_BY_ID: "oauth/tokens",
            GET_USER_CLIENTS: "oauth/clients",
            CREATE_USER_CLIENTS: "oauth/clients",
            EDIT_USER_CLIENT_BY_ID: "oauth/clients",
            DELETE_USER_CLIENT_BY_ID: "oauth/clients",
            GET_USER_AVAILABLE_AUTH_SCOPE: "oauth/scopes",
            GET_USER_PERSONAL_ACCESS_TOKEN: "oauth/personal-access-tokens",
            CREATE_USER_PERSONAL_ACCESS_TOKEN: "oauth/personal-access-tokens",
            DELETE_USER_PERSONAL_ACCESS_TOKEN_BY_ID: "oauth/personal-access-tokens",
        },
        DATI_AZIENDA: { 
            GET_ALL: "app/api/datiAzienda/view/datiAzienda",
            LISTA_CONTI_DATI_AZIENDA_BY_ID: "app/api/datiAzienda/view/datiAzienda/conto",
            GET_CONFIG_DATA: "app/api/datiAzienda/view/datiAzienda/config",
            CREATE_DATI_AZIENDA_INVITO: "app/api/datiAzienda/new",
            EDIT_DATI_AZIENDA_BY_ID: "app/api/datiAzienda/update",
        },
        INVITA_AMICI: null,
        PASSWORD: {
            UPDATE: "api/user/update-password",
            FORGOT: "api/user/auth/forgot-password",
            RESET: "api/user/auth/reset-password",
        },
        SEZIONE_UTENTI: null,
    },
} as const;
